/* Sample Code for Creating SQL Data Warehouse for Alexandria Community Indicators */

/* Code below should be replaced with code to import CSV files containing these data points */

/*insert records into REGION table*/
insert into region values (1,'Northeast');
insert into region values (2,'South');
insert into region values (3,'Midwest');
insert into region values (4,'West');

/*insert records into THEME table*/
insert into theme values ('Sense of community','An Alexandria where building a sense of community and helping one another are essential');
insert into theme values ('Basic needs','An Alexandria where meeting basic needs such as food, clothing, shelter, and affordable housing is a priority for each individual');
insert into theme values ('Diversity','An Alexandria that celebrates racial, ethnic, and gender diversity and supports people of all ages, abilities, and sexual orientation');
insert into theme values ('Access to health care','An Alexandria where all residents, regardless of their ability to pay, can access quality health care that focuses on prevention, treatment, and wellness');
insert into theme values ('Built environment','An Alexandria where everyone has access to transportation options, trails, parks, open space and recreation opportunities');
insert into theme values ('Crime and safety','An Alexandria where people are safe in their homes and walking in their neighborhoods, unafraid of crime, violence and domestic abuse');
insert into theme values ('Mental health','An Alexandria where safeguarding emotional and mental health is a priority and there is adequate provision of mental health services');
insert into theme values ('Substance abuse prevention','An Alexandria where its residents support and are engaged in efforts to prevent the abuse of alcohol, tobacco and other drugs and where treatment for substance use problems is readily available');
insert into theme values ('Food and nutrition','An Alexandria where all residents can access safe and healthy foods and are able to practice healthy eating habits');
insert into theme values ('Cleanliness and beautification','An Alexandria where our houses, streets, neighborhoods and parks are clean and well-kept, as well as free of garbage, environmental hazards, and pests so that everyone can fully enjoy our beautiful city');
insert into theme values ('Employment opportunities','An Alexandria where meaningful employment opportunities are available to all');

/*insert records into timePeriod table*/
insert into timePeriod values (2000,0,0);
insert into timePeriod values (2000,1,1);
insert into timePeriod values (2000,1,2);
insert into timePeriod values (2000,1,3);
insert into timePeriod values (2000,2,4);
insert into timePeriod values (2000,2,5);
insert into timePeriod values (2000,2,6);
insert into timePeriod values (2000,3,7);
insert into timePeriod values (2000,3,8);
insert into timePeriod values (2000,3,9);
insert into timePeriod values (2000,4,10);
insert into timePeriod values (2000,4,11);
insert into timePeriod values (2000,4,12);
insert into timePeriod values (2001,0,0);
insert into timePeriod values (2001,1,1);
insert into timePeriod values (2001,1,2);
insert into timePeriod values (2001,1,3);
insert into timePeriod values (2001,2,4);
insert into timePeriod values (2001,2,5);
insert into timePeriod values (2001,2,6);
insert into timePeriod values (2001,3,7);
insert into timePeriod values (2001,3,8);
insert into timePeriod values (2001,3,9);
insert into timePeriod values (2001,4,10);
insert into timePeriod values (2001,4,11);
insert into timePeriod values (2001,4,12);
insert into timePeriod values (2002,0,0);
insert into timePeriod values (2002,1,1);
insert into timePeriod values (2002,1,2);
insert into timePeriod values (2002,1,3);
insert into timePeriod values (2002,2,4);
insert into timePeriod values (2002,2,5);
insert into timePeriod values (2002,2,6);
insert into timePeriod values (2002,3,7);
insert into timePeriod values (2002,3,8);
insert into timePeriod values (2002,3,9);
insert into timePeriod values (2002,4,10);
insert into timePeriod values (2002,4,11);
insert into timePeriod values (2002,4,12);
insert into timePeriod values (2003,0,0);
insert into timePeriod values (2003,1,1);
insert into timePeriod values (2003,1,2);
insert into timePeriod values (2003,1,3);
insert into timePeriod values (2003,2,4);
insert into timePeriod values (2003,2,5);
insert into timePeriod values (2003,2,6);
insert into timePeriod values (2003,3,7);
insert into timePeriod values (2003,3,8);
insert into timePeriod values (2003,3,9);
insert into timePeriod values (2003,4,10);
insert into timePeriod values (2003,4,11);
insert into timePeriod values (2003,4,12);
insert into timePeriod values (2004,0,0);
insert into timePeriod values (2004,1,1);
insert into timePeriod values (2004,1,2);
insert into timePeriod values (2004,1,3);
insert into timePeriod values (2004,2,4);
insert into timePeriod values (2004,2,5);
insert into timePeriod values (2004,2,6);
insert into timePeriod values (2004,3,7);
insert into timePeriod values (2004,3,8);
insert into timePeriod values (2004,3,9);
insert into timePeriod values (2004,4,10);
insert into timePeriod values (2004,4,11);
insert into timePeriod values (2004,4,12);
insert into timePeriod values (2005,0,0);
insert into timePeriod values (2005,1,1);
insert into timePeriod values (2005,1,2);
insert into timePeriod values (2005,1,3);
insert into timePeriod values (2005,2,4);
insert into timePeriod values (2005,2,5);
insert into timePeriod values (2005,2,6);
insert into timePeriod values (2005,3,7);
insert into timePeriod values (2005,3,8);
insert into timePeriod values (2005,3,9);
insert into timePeriod values (2005,4,10);
insert into timePeriod values (2005,4,11);
insert into timePeriod values (2005,4,12);
insert into timePeriod values (2006,0,0);
insert into timePeriod values (2006,1,1);
insert into timePeriod values (2006,1,2);
insert into timePeriod values (2006,1,3);
insert into timePeriod values (2006,2,4);
insert into timePeriod values (2006,2,5);
insert into timePeriod values (2006,2,6);
insert into timePeriod values (2006,3,7);
insert into timePeriod values (2006,3,8);
insert into timePeriod values (2006,3,9);
insert into timePeriod values (2006,4,10);
insert into timePeriod values (2006,4,11);
insert into timePeriod values (2006,4,12);
insert into timePeriod values (2007,0,0);
insert into timePeriod values (2007,1,1);
insert into timePeriod values (2007,1,2);
insert into timePeriod values (2007,1,3);
insert into timePeriod values (2007,2,4);
insert into timePeriod values (2007,2,5);
insert into timePeriod values (2007,2,6);
insert into timePeriod values (2007,3,7);
insert into timePeriod values (2007,3,8);
insert into timePeriod values (2007,3,9);
insert into timePeriod values (2007,4,10);
insert into timePeriod values (2007,4,11);
insert into timePeriod values (2007,4,12);
insert into timePeriod values (2008,0,0);
insert into timePeriod values (2008,1,1);
insert into timePeriod values (2008,1,2);
insert into timePeriod values (2008,1,3);
insert into timePeriod values (2008,2,4);
insert into timePeriod values (2008,2,5);
insert into timePeriod values (2008,2,6);
insert into timePeriod values (2008,3,7);
insert into timePeriod values (2008,3,8);
insert into timePeriod values (2008,3,9);
insert into timePeriod values (2008,4,10);
insert into timePeriod values (2008,4,11);
insert into timePeriod values (2008,4,12);
insert into timePeriod values (2009,0,0);
insert into timePeriod values (2009,1,1);
insert into timePeriod values (2009,1,2);
insert into timePeriod values (2009,1,3);
insert into timePeriod values (2009,2,4);
insert into timePeriod values (2009,2,5);
insert into timePeriod values (2009,2,6);
insert into timePeriod values (2009,3,7);
insert into timePeriod values (2009,3,8);
insert into timePeriod values (2009,3,9);
insert into timePeriod values (2009,4,10);
insert into timePeriod values (2009,4,11);
insert into timePeriod values (2009,4,12);
insert into timePeriod values (2010,0,0);
insert into timePeriod values (2010,1,1);
insert into timePeriod values (2010,1,2);
insert into timePeriod values (2010,1,3);
insert into timePeriod values (2010,2,4);
insert into timePeriod values (2010,2,5);
insert into timePeriod values (2010,2,6);
insert into timePeriod values (2010,3,7);
insert into timePeriod values (2010,3,8);
insert into timePeriod values (2010,3,9);
insert into timePeriod values (2010,4,10);
insert into timePeriod values (2010,4,11);
insert into timePeriod values (2010,4,12);
insert into timePeriod values (2011,0,0);
insert into timePeriod values (2011,1,1);
insert into timePeriod values (2011,1,2);
insert into timePeriod values (2011,1,3);
insert into timePeriod values (2011,2,4);
insert into timePeriod values (2011,2,5);
insert into timePeriod values (2011,2,6);
insert into timePeriod values (2011,3,7);
insert into timePeriod values (2011,3,8);
insert into timePeriod values (2011,3,9);
insert into timePeriod values (2011,4,10);
insert into timePeriod values (2011,4,11);
insert into timePeriod values (2011,4,12);
insert into timePeriod values (2012,0,0);
insert into timePeriod values (2012,1,1);
insert into timePeriod values (2012,1,2);
insert into timePeriod values (2012,1,3);
insert into timePeriod values (2012,2,4);
insert into timePeriod values (2012,2,5);
insert into timePeriod values (2012,2,6);
insert into timePeriod values (2012,3,7);
insert into timePeriod values (2012,3,8);
insert into timePeriod values (2012,3,9);
insert into timePeriod values (2012,4,10);
insert into timePeriod values (2012,4,11);
insert into timePeriod values (2012,4,12);
insert into timePeriod values (2013,0,0);
insert into timePeriod values (2013,1,1);
insert into timePeriod values (2013,1,2);
insert into timePeriod values (2013,1,3);
insert into timePeriod values (2013,2,4);
insert into timePeriod values (2013,2,5);
insert into timePeriod values (2013,2,6);
insert into timePeriod values (2013,3,7);
insert into timePeriod values (2013,3,8);
insert into timePeriod values (2013,3,9);
insert into timePeriod values (2013,4,10);
insert into timePeriod values (2013,4,11);
insert into timePeriod values (2013,4,12);

/*insert records into dataSource table*/
insert into dataSource values ('ACS','American Community Survey');
insert into dataSource values ('Census','Decennial Census');
insert into dataSource values ('HSCC','Homeless Services Coordinating Committee');
insert into dataSource values ('MCOG','Metropolitan Washington Council of Governments');
insert into dataSource values ('ADH','Alexandria Department of Housing');
insert into dataSource values ('ADF','Alexandria Department of Finance');
insert into dataSource values ('VDSS','Virginia Department of Social Services');
insert into dataSource values ('ACPS','Alexandria City Public Schools');
insert into dataSource values ('VDE','Virginia Department of Education');
insert into dataSource values ('FNS','US Department of Agriculture, Food and Nutrition Service');
insert into dataSource values ('DAS','Developmental Assets Survey, Alexandria City Public Schools');
insert into dataSource values ('OHR','Office of Human Rights, City of Alexandria');
insert into dataSource values ('BRFSS','Virginia Behavioral Risk Factor Surveillance System');
insert into dataSource values ('VDH','Virginia Department of Health');
insert into dataSource values ('VDMAS','Virginia Department of Medical Assistance Services');
insert into dataSource values ('VDHS','Virginia Department of Health Statistics');
insert into dataSource values ('GIS','GIS Division, Department of Planning and Zoning, City of Alexandria');
insert into dataSource values ('DTES','Department of Transportation and Environmental Services, City of Alexandria');
insert into dataSource values ('DRPCA','Department of Recreation, Parks, and Cultural Activities, City of Alexandria');
insert into dataSource values ('ADCHS','Alexandria Department of Community and Human Services');
insert into dataSource values ('CCFCWS','Center for Children and Families, Child Welfare Services');
insert into dataSource values ('APD','Alexandria Police Department');
insert into dataSource values ('YRBSS','Youth Risk Behavior Surveillance System, Alexandria City Public Schools');
insert into dataSource values ('CDC','Centers for Disease Control and Prevention');
insert into dataSource values ('SAMHSA','Substance Abuse and Mental Health Services Administration');
insert into dataSource values ('ADHEHD','Alexandria Department of Health, Environmental Health Division');
insert into dataSource values ('AOEQ','Alexandria Office of Environmental Quality');
insert into dataSource values ('VAWC','Virginia American Water Company');
insert into dataSource values ('ODW','Office of Drinking Water, Virginia Department of Health');
insert into dataSource values ('VEC','Virginia Employment Commission');
insert into dataSource values ('CAFR','City of Alexandria Financial Report');
insert into dataSource values ('BLS','US Department of Labor, Bureau of Labor Statistics');
insert into dataSource values ('AEDP','Alexandria Economic Development Partnership');

/*insert records into indicatorType table*/
insert into indicatorType values ('Pct_Res_StrongCommunity','Percentage of residents who report a strong sense of community',1,'2','5','0','3','');
insert into indicatorType values ('Pct_Res_Volunteer','Percentage of residents who report volunteering in the last 12 months',1,'2','5','0','3','');
insert into indicatorType values ('Pct_Inc_HsgCost','Percentage of income paid toward housing',2,'1','4','1','1','');
insert into indicatorType values ('Num_HomelessPersons','Number of homeless persons',2,'1','4','0','1','');
insert into indicatorType values ('Num_HsgUnits_50PctMedian','Number of housing units available for households earning below 50% of median income',2,'1','4','1','1','');
insert into indicatorType values ('Median_GrossRent','Median gross rent',2,'1','4','1','1','');
insert into indicatorType values ('Num_RealEstate_Foreclosures','Number of Real Estate foreclosures',2,'1','4','1','1','');
insert into indicatorType values ('Num_Res_FoodStamps','Number of Food Stamp recipients',2,'1','4','0','1','');
insert into indicatorType values ('Pct_Stud_FreeRedCostMeals','Percentage of ACPS children eligible to receive free and reduced cost meals at school',2,'1','4','1','1','');
insert into indicatorType values ('Pct_Youth_Encouraged','Percentage of youth who feel encouraged by adults',3,'1','2','0','2','');
insert into indicatorType values ('Pct_Commissions_Reflect_Demog','City commissions that reflect demographic makeup of Alexandria',3,'3','2','0','3','');
insert into indicatorType values ('Tolerance_Index','Tolerance index',3,'2','2','0','3','');
insert into indicatorType values ('Pct_Adults_with_Healthcare','Percentage of adults who currently report having any kind of health care coverage',4,'1','2','0','2','');
insert into indicatorType values ('Num_Child_SCHIP','Number of children participating in the State Childrens Health Insurance Program (SCHIP)',4,'1','4','2','1','');
insert into indicatorType values ('Pct_Res_NoDoctor_Due_to_Cost','Percentage of people indicating they needed to see a doctor in the past year and could not due to cost',4,'1','2','0','2','');
insert into indicatorType values ('Pct_Prenatal_1stTrimester','Percentage of women who received prenatal care in the first trimester of pregnancy',4,'1','4','0','1','');
insert into indicatorType values ('Rate_NewHIVCases_100000','Number of newly diagnosed cases of HIV per 100,000 population',4,'1','4','2','1','');
insert into indicatorType values ('Pct_Adults_Health_GoodExcellent','Percentage of adults who rated their health good to excellent',4,'1','4','2','1','');
insert into indicatorType values ('Pct_Adults_Got_FluVaccine','Percentage of adults who received seasonal influenza vaccine',4,'1','4','0','2','');
insert into indicatorType values ('Pct_Adults_OverweightObese','Percentage of adults overweight or obese',4,'1','3','0','2','');
insert into indicatorType values ('Rate_HeartDiseaseMortal_100000','Heart disease mortality rate per 100,000 population',4,'1','3','0','2','');
insert into indicatorType values ('Rate_CancerMortality_100000','Cancer mortality rate per 100,000',4,'1','4','0','1','');
insert into indicatorType values ('Rate_InfantMortality_1000','Infant mortality per 1000 live births',4,'1','4','0','1','');
insert into indicatorType values ('Pct_Women_Prenatal_1stTri','Percentage of women who received prenatal care in the first trimester of pregnancy',4,'1','3','0','1','');
insert into indicatorType values ('Rate_TeenPregnancy_1000','Teen pregnancy rate',4,'1','3','0','1','');
insert into indicatorType values ('Pct_Res_WalktoWork','Percentage of Alexandria residents walking to work',5,'1','3','1','1','');
insert into indicatorType values ('Pct_Res_BiketoWork','Percentage of Alexandria residents who bike to work',5,'1','3','1','1','');
insert into indicatorType values ('Pct_TreeCanopyCoverage','Percentage of tree canopy coverage',5,'1','3','1','2','');
insert into indicatorType values ('Pct_Res_LiveNearPublicTransit','Percentage of residents who live within a walkable quarter mile of a public transportation point',5,'1','4','1','1','');
insert into indicatorType values ('Miles_SharedUsePaths','Miles of designated shared-use paths and bike lanes relative to street miles',5,'1','3','0','2','');
insert into indicatorType values ('Rate_OpenSpaceAcres_1000','Open space acres per 1000 residents',5,'3','3','0','2','');
insert into indicatorType values ('Pct_Res_TakePublicTransit_Work','Percentage of residents who take public transportation to work',5,'1','4','1','1','');
insert into indicatorType values ('Num_ChildAbuseInvestigations','Child abuse and neglect investigations with a founded disposition',6,'1','3','2','1','');
insert into indicatorType values ('Num_Perceive_PhysicalSafety','Perception of physical safety in the community',6,'2','5','2','3','');
insert into indicatorType values ('Num_MajorCrimes_Total','Number of major crimes',6,'1','4','1','1','Can break down into 7 categories');
insert into indicatorType values ('Num_NuisanceCrimes','Number of nuisance crimes',6,'1','4','1','1','');
insert into indicatorType values ('Avg_ResponseTime_StructureFires','Average response time in minutes to Alexandria structure fires',6,'1','3','0','1','');
insert into indicatorType values ('Pct_DisasterSupplyKit_Prepared','Percentage of population reporting a Disaster Supply Kit with emergency supplies such as water, food, and medicine has been prepared in home',6,'2','5','0','3','');
insert into indicatorType values ('Pct_Adults_Depress_Get_Care','Percentage of adults with recognized depression who receive treatment',7,'2','5','0','3','');
insert into indicatorType values ('Pct_Adults_Got_MentalHealthCare','Percentage of adults needing mental health care who stated that they did obtain professional help for emotional or mental health issues in the past year',7,'2','5','0','3','');
insert into indicatorType values ('Pct_Stud_Considered_Suicide','Percentage of adolescents who reported that they have seriously considered suicide',7,'1','2','0','2','');
insert into indicatorType values ('Num_MentallyUnhealthyDays_Last30','Mentally unhealthy days during the last 30 days',7,'1','2','0','2','');
insert into indicatorType values ('Pct_Adults_Smoke','Percentage of adults who smoke cigarettes',8,'1','3','0','2','');
insert into indicatorType values ('Pct_Youth_NeverSmoked','Percentage of youth who never smoked cigarettes',8,'1','2','0','2','');
insert into indicatorType values ('Pct_Youth_Used_Alcohol_Last30','Percentage of adolescents who report having used alcohol in the past 30 days',8,'1','2','0','2','Broken out by grade, 7-12');
insert into indicatorType values ('Pct_Youth_Used_IllicitRx','Percentage of youth who report illicitly using prescription drugs',8,'3','2','0','3','');
insert into indicatorType values ('Pct_Res_SpecTrtmnt_SubAbuse','Percentage of residents who received specialty treatment for substance abuse or dependence',8,'3','2','0','3','');
insert into indicatorType values ('Pct_Adults_Eat_5Plus_FruitsVeg','Percentage of adults eating 5 or more fruits or vegetables a day',9,'1','2','0','2','');
insert into indicatorType values ('Pct_Tracts_HealthierFoodRetail','Percentage of Alexandria Census tracts that have healthier daily food retailers located within the tract or within one-half mile of tract boundaries',9,'1','3','1','3','');
insert into indicatorType values ('Pct_Res_Participate_WIC','Percentage of residents participating in the WIC program',9,'1','4','0','1','');
insert into indicatorType values ('Avg_Num_FoodSafety_Violations','Average number of critical violations per food establishment inspection in Alexandria',9,'1','3','0','1','');
insert into indicatorType values ('Num_AirQualityActionDays','Number of air quality action days',10,'1','4','0','1','');
insert into indicatorType values ('Num_Hazard_Pest_Complaints','Number of environmental hazards and pests complaints',10,'1','3','0','1','');
insert into indicatorType values ('Pct_SolidWaste_Recycled','Percentage of solid waste recycled',10,'1','3','0','2','');
insert into indicatorType values ('Num_WaterQuality_Violations','Number of water quality violations',10,'1','4','0','1','');
insert into indicatorType values ('Median_Household_Income','Median household income',11,'1','4','1','1','');
insert into indicatorType values ('Pct_Age16_64_In_Workforce','Percentage of population ages 16-64 in the workforce',11,'1','4','1','1','');
insert into indicatorType values ('Pct_Res_BelowPoverty','Percentage of population below the poverty level',11,'1','4','1','1','');
insert into indicatorType values ('Rate_OnTimeGraduation','ACPS On-Time Graduation Rate',11,'1','2','0','1','');
insert into indicatorType values ('Pct_Res_Unemployed','Prevalence of local unemployment',11,'1','4','0','1','');
insert into indicatorType values ('Pct_Adults_Diploma_or_GED','Percentage of adults with at least a high school diploma or general education diploma',11,'1','4','1','1','');
insert into indicatorType values ('Pct_Retail_Occupancy','Percentage retail occupancy',11,'3','1','0','1','');
